### ISSUE TITLE
minification typescript

### ISSUE THREAD

**Issue by flieks** [aurelia/webpack-plugin#43]
Probably this is a webpack issue but anyone knows how to get minification for webpack?
Using ts-loader.

There is a [github issue](https://github.com/TypeStrong/ts-loader/issues/224) about it..

Thanks

**Comment by flieks** [comment]
Ok maybe it was minified but the file is 2.4MB. (0-1.0.0-beta.1.3.0.js)

i puted 
`new webpack.optimize.UglifyJsPlugin()`
in the plugins[]
but that does produce the exact same file.

**Comment by niieani** [comment]
This is not an issue of Aurelia. Please use the awesome-typescript-loader instead of the ts-loader. Also, look into the latest Webpack Skeletons to see how this is solved there (we do minify Aurelia and it's about 310KB when bundled).

**Comment by flieks** [comment]
Thanks @niieani 
I did copy the latest webpack config from the TS skeleton.
Just having issues with [aurelia-breeze](https://github.com/jdanyow/aurelia-breeze/issues/33) now
my config in [gist](https://gist.github.com/flieks/ebd642a5c021775e9cde39bd8ee04fdd)

**Comment by niieani** [comment]
aurelia breeze might require build resources to be defined. See the Readme of Webpack skeleton.

**Comment by flieks** [comment]
Thanks,
I added yseterday
```
"aurelia": {
  "build": {
    "resources": [
      "aurelia-breeze"
    ]
  }
}
```
but that still doesn't work.

In animation-main.ts:
```
aurelia.use
    .standardConfiguration()
    .plugin('aurelia-breeze')
```
aurelia-breeze also uses "breeze" which is in the package.json dependencies

**Comment by niieani** [comment]
What I meant is that `aurelia-breeze` might need its own set of build resources.

**Comment by flieks** [comment]
so @jdanyow (maker aurelia-breeze) needs to provide this or how can i find out what to put there ?

**Comment by niieani** [comment]
@flieks I don't have time right now to investigate, I can take a look at some point in the future. Not sure if there are any build resources to provide by Jeremy, it was a wild guess.

**Comment by flieks** [comment]
ok thanks already for quick replies and keep up the good work :)
